sudo: false
language: ruby
rvm:
  -  2.5.3
cache:
  bundler: true
  directories:
    - $HOME/perl5/
before_script:
  # NOTE: we need LaTeXML including commit
  # https://github.com/brucemiller/LaTeXML/commit/9a0e7dc5829c1218e409da716d2a50b81472c38e
  # related to issue https://github.com/brucemiller/LaTeXML/issues/1153
  # but that's planned for release on 0.85 (early 2020). We can't get it from apt yet.
  - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  # NOTE: cpanminus insists on installing LaTeXML in /tmp/* (why?);
  # since that can't be cached at least we skip tests.
  - cpanm --notest git://github.com/brucemiller/LaTeXML.git@9a0e7dc5
script:
  - bundle exec rake test
