= tex2mn manual
:repo-url: https://github.com/metanorma/tex2mn
:repo-tag: master
:repo-blob-url: {repo-url}/blob/{repo-tag}
:repo-tree-url: {repo-url}/tree/{repo-tag}
:toc:

:leveloffset: +1

= Reading the manual
:canidothis: true

Since `tex2mn` is a tool to transform `LaTeX` source files, some familiarity with `LaTeX` and its de-facto standard packages is assumed.

We will graphically differentiate between:

* `\standard` well-known macros which have standard behaviour, and
* `*\NonStandard*` macros which are unique to `tex2mn` and will be documented thoroughly.

[NOTE]
====
In either case we will point out which `LaTeX` packages are used to define them (if any).
====

Code samples will _always_ be presented as pairs of equivalent `LaTeX`/`AsciiDoc` listings to help you acquaint with both regardless of which side you're more familiar with:

[cols="5a,4a"]
|===
|[source,latex]
----
What a \textbf{bold} statement.
----
|[source,asciidoc]
----
What a *bold* statement.
----
|===

That's it.
You can confidently start reading, now!

If you happen to find any unexpected behaviour in the software or lack of clarity in the manual, please report it on our {repo-url}/issues[issue tracker] to help us make this tool better for everyone.

:leveloffset!:
// include::text_formatting.adoc[leveloffset=+1]
// include::paragraph_formatting.adoc[leveloffset=+1]