= Text formatting

NOTE: These features are verified by tests in {repo-blob-url}/test/test_text_formatting.rb[test_text_formatting.rb].

You can set bold, italic, monospace and small caps text using respectively `\textbf`, `\textit`, `\texttt` and `\textsc`.

[cols="a,a"]
|===
|[source,latex]
----
\textbf{Bold} text.

\textit{Italic} text.

\texttt{Monospace} text.

\textsc{Small caps} text.
----
|[source,asciidoc]
----
**Bold** text.

__Italic__ text.

``Monospace`` text.

[smallcap]#Small caps# text.
----
|===

The _switch_ versions of these macros are available too: `\bfseries`, `\itshape`, `\ttfamily` and `\scshape`.

[cols="a,a"]
|===
|[source,latex]
----
{\bfseries Bold} text.

{\itshape Italic} text.

{\ttfamily Monospace} text.

{\scshape Small caps} text.
----
|[source,asciidoc]
----
**Bold** text.

__Italic__ text.

``Monospace`` text.

[smallcap]#Small caps# text.
----
|===

You can set strikethrough, superscript and subscript text using respectively `*\textst*`, `\textsuperscript` and `\textsubscript`.

[cols="a,a"]
|===
|[source,latex]
----
Strikethrough \textst{text}.

Superscript \textsuperscript{text}.

Subscript \textsubscript{text}.
----
|[source,asciidoc]
----
Strikethrough [strike]#text#.

Superscript ^text^.

Subscript ~text~.
----
|===

NOTE: Strikethrough text is implemented using the {ctan-pkg-url}/ulem[ulem] package.

The `\emph` macro for emphasized text is supported, but without its normal nesting behaviour: AsciiDoc output is able to represent only the outer level.

[cols="a,a"]
|===
|[source,latex]
----
Emphasized \emph{text}.

Emphasized \emph{text with \emph{extra} emphasis}.
----
|[source,asciidoc]
----
Emphasized __text__.

Emphasized __text with extra emphasis__.
----
|===