name: windows

on: [push, pull_request]

jobs:
  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.5.5']
        perl: ['5.30']
    steps:

      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup Perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: Add Strawberry Perl to PATH (*before* MSYS Perl!)
        run: |
          echo "##[add-path]C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"

      # NOTE: we need LaTeXML including commit
      # https://github.com/brucemiller/LaTeXML/commit/9a0e7dc5829c1218e409da716d2a50b81472c38e
      # related to issue https://github.com/brucemiller/LaTeXML/issues/1153
      # but that's planned for release on 0.85 (early 2020).
      - name: Install LaTeXML
        run: cpanm --verbose --no-interactive --notest git://github.com/brucemiller/LaTeXML.git@9a0e7dc5

      - name: Setup Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'

      - name: Cache gems
        id: cache-gems
        uses: actions/cache@v1
        with:
          path: ${{ runner.tool_cache }}/Ruby/2.5.5/x64/lib/ruby/gems
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}

      - name: Update gems
        run: |
          gem install bundler -v "~> 2"
          bundle update --bundler
          bundle install --jobs 4 --retry 3

      - name: Run specs
        run: |
          bundle exec rake test
